Repository Unidata/MetPy, pull requests merged in 2018-02, with the labels that each got.

#736 Fix Level3File
  .codeclimate.yml
  metpy/io/nexrad.py
  metpy/io/tests/test_nexrad.py
Labels: Area: IO, Type: Bug

#744 Fix dependecies. #734
  setup.py
Labels: Area: Infrastructure, Type: Maintenance

#745 Add AMS talk
  .gitignore
  docs/index.rst
Labels: Area: Docs, Type: Enhancement

#739 Ageostrophic wind
  metpy/calc/kinematics.py
  metpy/calc/tests/test_kinematics.py
Labels: Area: Calc, Type: Feature

#740 Fix return types in docstrings of logo functions
  metpy/plots/_util.py
Labels: Area: Docs, Type: Maintenance

#749 MNT: Fix Travis testing with CartoPy
  .travis.yml
  metpy/plots/tests/test_station_plot.py
Labels: Area: Infrastructure, Type: Maintenance

#751 MNT: Tweak license text and update year
  CONTRIBUTING.md
  LICENSE
  examples/formats/GINI_Water_Vapor.py
  examples/formats/NEXRAD_Level_2_File.py
  examples/formats/NEXRAD_Level_3_File.py
  examples/isentropic_example.py
  examples/sigma_to_pressure_interpolation.py
  metpy/calc/kinematics.py
  metpy/calc/tests/test_kinematics.py
  metpy/calc/tests/test_thermo.py
  metpy/calc/tests/test_tools.py
  metpy/calc/thermo.py
  metpy/calc/tools.py
  metpy/constants.py
  metpy/plots/_util.py
  metpy/plots/tests/test_util.py
Labels: Area: Infrastructure, Type: Maintenance

#738 Barb unit conversion at plot time
  .codeclimate.yml
  metpy/plots/skewt.py
  metpy/plots/station_plot.py
  metpy/plots/tests/baseline/test_barb_no_default_unit_conversion.png
  metpy/plots/tests/baseline/test_barb_unit_conversion.png
  metpy/plots/tests/baseline/test_skewt_barb_no_default_unit_conversion.png
  metpy/plots/tests/baseline/test_skewt_barb_unit_conversion.png
  metpy/plots/tests/test_skewt.py
  metpy/plots/tests/test_station_plot.py
Labels: Area: Plots, Type: Enhancement

#748 Add saturation equivalent potential temperature
  metpy/calc/tests/test_thermo.py
  metpy/calc/thermo.py
Labels: Area: Calc, Type: Feature

#741 Adds custom grid boundary to interpolate
  metpy/gridding/gridding_functions.py
  metpy/gridding/tests/test_gridding_functions.py
Labels: Area: Calc, Type: Enhancement

#758 Fix rendering issues in Montgomery Streamfunction
  metpy/calc/kinematics.py
Labels: Area: Docs, Type: Maintenance

#759 MNT: use `mpcalc` as import alias for `metpy.calc`
  examples/calculations/Dewpoint_and_Mixing_Ratio.py
  examples/isentropic_example.py
  examples/sigma_to_pressure_interpolation.py
  talks/2015 Unidata Users Workshop.ipynb
  talks/MetPy Exercise.ipynb
Labels: Area: Docs, Area: Examples, Type: Maintenance
