Repository Unidata/MetPy, pull requests merged in 2021-11, with the labels that each got.

#2178 CI: Update nightly builds with cartopy build changes from #2165
  .github/workflows/nightly-builds.yml
Labels: Area: Infrastructure, Type: Maintenance

#2152 allow range for contours
  src/metpy/plots/declarative.py
  tests/plots/test_declarative.py
Labels: Type: Enhancement, Area: Plots

#2184 Correct docs for search_radius in interpolate functions
  src/metpy/interpolate/grid.py
  src/metpy/interpolate/points.py
Labels: Type: Bug, Area: Docs, Area: Calc

#2200 Fix `dev` docs deploy
  .github/workflows/docs.yml
Labels: Area: Infrastructure, Type: Bug

#2196 Add field for traceback to bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Area: Infrastructure, Type: Enhancement

#2156 add smoothing for declarative
  src/metpy/plots/declarative.py
  tests/plots/baseline/test_declarative_smooth_field.png
  tests/plots/test_declarative.py
Labels: Type: Enhancement, Area: Plots

#2201 Add flake8-pie to flake8 plugins
  ci/linting_requirements.txt
  examples/gridding/Point_Interpolation.py
  src/metpy/calc/basic.py
  src/metpy/calc/thermo.py
  src/metpy/deprecation.py
  src/metpy/interpolate/slices.py
  src/metpy/io/gempak.py
  src/metpy/io/gini.py
  src/metpy/io/nexrad.py
  src/metpy/io/station_data.py
  src/metpy/plots/declarative.py
  src/metpy/plots/skewt.py
  src/metpy/xarray.py
  tests/calc/test_calc_tools.py
  tests/units/test_units.py
Labels: Area: Infrastructure, Type: Maintenance

#2206 Readme Tweaks
  README.md
Labels: Type: Maintenance, Area: Docs, Type: Enhancement

#2207 CI: Remove jinja pin
  ci/doc_requirements.txt
Labels: Area: Infrastructure, Type: Maintenance

#2177 Python 3.10
  .github/actions/build-docs/action.yml
  .github/actions/install-conda/action.yml
  .github/actions/install-pypi/action.yml
  .github/actions/setup-proj/action.yml
  .github/workflows/docs.yml
  .github/workflows/tests-pypi.yml
  setup.cfg
Labels: Type: Maintenance

#2155 Add zoom interpolation function
  docs/_templates/overrides/metpy.calc.rst
  src/metpy/calc/basic.py
  src/metpy/plots/declarative.py
  tests/calc/test_basic.py
  tests/plots/baseline/test_declarative_smooth_contour.png
  tests/plots/baseline/test_declarative_smooth_contour_order.png
  tests/plots/test_declarative.py
Labels: Type: Enhancement, Area: Plots

#2216 Correct array shape typos in natural_neighbor_to_grid
  src/metpy/interpolate/grid.py
Labels: Type: Bug, Area: Docs, Area: Gridding

#2179 Matplotlib Updates
  ci/requirements.txt
  examples/formats/NEXRAD_Level_2_File.py
  setup.cfg
  src/metpy/plots/_mpl.py
  src/metpy/plots/declarative.py
  src/metpy/plots/skewt.py
  tests/plots/baseline/test_arrow_projection.png
  tests/plots/baseline/test_barb_projection.png
  tests/plots/baseline/test_declarative_contour.png
  tests/plots/baseline/test_declarative_contour_cam.png
  tests/plots/baseline/test_declarative_events.png
  tests/plots/baseline/test_declarative_figsize.png
  tests/plots/baseline/test_declarative_region_modifier_zoom_out.png
  tests/plots/baseline/test_declarative_smooth_contour.png
  tests/plots/baseline/test_gempak_color_image_compare.png
  tests/plots/baseline/test_gempak_color_xw_image_compare.png
  tests/plots/baseline/test_hodograph_api.png
  tests/plots/baseline/test_hodograph_plot_layers.png
  tests/plots/baseline/test_hodograph_plot_layers_bound_units.png
  tests/plots/baseline/test_hodograph_plot_layers_different_units.png
  tests/plots/baseline/test_hodograph_units.png
  tests/plots/baseline/test_skewt_api_units.png
  tests/plots/test_cartopy_utils.py
  tests/plots/test_declarative.py
  tests/plots/test_skewt.py
  tests/plots/test_station_plot.py
  tests/plots/test_util.py
Labels: Type: Maintenance, Area: Tests, Area: Plots

#2218 Updates for CI pipeline
  .codecov.yml
  .github/actions/build-docs/action.yml
  .github/actions/install-conda/action.yml
  .github/actions/install-pypi/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/setup-proj/action.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/linting.yml
  .github/workflows/nightly-builds.yml
  .github/workflows/release.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  ci/filter_links.py
Labels: Area: Infrastructure, Type: Bug

#2219 Fixes for nightly CI run
  .github/actions/build-docs/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/linting.yml
  .github/workflows/nightly-builds.yml
Labels: Area: Infrastructure, Type: Bug, Type: Maintenance

#2221 Fix linkchecker build
  CONTRIBUTING.md
  docs/api/references.rst
  docs/conf.py
  examples/gridding/Point_Interpolation.py
Labels: Type: Maintenance, Area: Docs

#2231 Fix GEMPAK date parsing
  src/metpy/io/gempak.py
  src/metpy/static-data-manifest.txt
  staticdata/sfc_obs.gem
  tests/io/test_gempak.py
Labels: Type: Bug, Area: IO
