Repository Unidata/MetPy, pull requests merged in 2021-04, with the labels that each got.

#1810 Remove stray viridis.tbl file
  src/metpy/plots/colortable_files/viridis.tbl
Labels: Area: Plots, Type: Maintenance

#1809 Use HTML API for release note links
  .github/workflows/draft-release.yml
Labels: Area: Infrastructure, Type: Bug

#1833 NEXRAD fixes
  src/metpy/io/nexrad.py
  src/metpy/static-data-manifest.txt
  staticdata/KVWX_20050626_221551.gz
  tests/io/test_nexrad.py
Labels: Area: IO, Type: Bug

#1819 Fix up internal multiplication by units
  setup.cfg
  src/metpy/calc/basic.py
  src/metpy/calc/cross_sections.py
  src/metpy/calc/indices.py
  src/metpy/calc/kinematics.py
  src/metpy/calc/thermo.py
  src/metpy/calc/tools.py
  src/metpy/constants.py
  src/metpy/io/metar.py
  src/metpy/io/station_data.py
  src/metpy/plots/declarative.py
  src/metpy/plots/skewt.py
  src/metpy/testing.py
  src/metpy/units.py
  src/metpy/xarray.py
  tests/calc/test_calc_tools.py
  tools/flake8-metpy/flake8_metpy.py
  tools/flake8-metpy/test_flake8_metpy.py
Labels: Area: Calc, Type: Bug

#1811 Fix wet_bulb_temperature with nans
  src/metpy/calc/thermo.py
  tests/calc/test_thermo.py
Labels: Area: Calc, Type: Bug

#1824 Set up a codespaces configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
Labels: Area: Infrastructure, Type: Feature

#1836 CI: Add workflow for managing version listing
  .github/workflows/doc-versions.yml
Labels: Area: Infrastructure, Type: Feature

#1840 lazy load station_info only when used #1320
  src/metpy/io/station_data.py
Labels: Area: IO, Type: Enhancement
