Repository Unidata/MetPy, pull requests merged in 2021-05, with the labels that each got.

#1842 Reduce duplication in minimum dependencies
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  ci/Minimum
  ci/requirements.txt
  docs/api/references.rst
  docs/devel/infrastructureguide.rst
  docs/userguide/installguide.rst
  setup.cfg
Labels: Area: Docs, Area: Infrastructure, Type: Enhancement

#1847 Move pre-release tests and docs builds out of PR CI
  .github/workflows/docs.yml
  .github/workflows/nightly-builds.yml
  .github/workflows/tests-pypi.yml
Labels: Area: Infrastructure, Type: Feature

#1850 CI Updates
  .github/codeql/codeql-config.yml
  .github/workflows/assign-milestone.yml
  .github/workflows/code-analysis.yml
  .github/workflows/docs.yml
  .github/workflows/draft-release.yml
  .github/workflows/nightly-builds.yml
  docs/api/references.rst
Labels: Area: Infrastructure, Type: Bug, Type: Enhancement, Type: Maintenance

#1861 Bump minimum dependency NumPy to >=1.17
  .github/workflows/nightly-builds.yml
  .github/workflows/tests-pypi.yml
  setup.cfg
Labels: Type: Maintenance

#1866 Fix assign milestone action
  .github/workflows/assign-milestone.yml
Labels: Area: Infrastructure, Type: Bug

#1869 BUG: Fix unit-handling in heat_index (Fixes #1867)
  src/metpy/calc/basic.py
Labels: Area: Calc, Type: Bug

#1885 Minor simplifications for the IO code
  src/metpy/io/_tools.py
  src/metpy/io/nexrad.py
Labels: Area: IO, Type: Maintenance

#1884 Copy method for declarative interface
  src/metpy/plots/declarative.py
  tests/plots/test_declarative.py
Labels: Area: Plots, Type: Enhancement
