Repository Unidata/MetPy, pull requests merged in 2022-02, with the labels that each got.

#2317 Drop Python 3.7
  .github/actions/install-conda/action.yml
  .github/actions/install-pypi/action.yml
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  README.md
  docs/index.rst
  docs/userguide/installguide.rst
  setup.cfg
  setup.py
  src/metpy/_version.py
Labels: Area: Infrastructure, Type: Maintenance

#2328 Bump test tolerance
  tests/plots/test_declarative.py
Labels: Type: Maintenance, Area: Tests, Area: Plots

#2329 Bump scipy and pandas minimum versions
  setup.cfg
Labels: Type: Maintenance

#2347 Update coord criteria regex so that X prefixes or _ infixes don't break it
  .codespellignore
  src/metpy/xarray.py
  tests/test_xarray.py
Labels: Type: Bug, Area: Xarray

#2348 Miscellaneous Maintenance
  .gitattributes
  ci/requirements.txt
  docs/conf.py
  examples/gridding/Natural_Neighbor_Verification.py
  src/metpy/cbook.py
  src/metpy/io/station_data.py
  tutorials/xarray_tutorial.py
Labels: Type: Bug, Type: Maintenance

#2357 Add a note to SUPPORT to just pick one
  SUPPORT.md
Labels: Area: Docs, Type: Enhancement
