Repository Unidata/MetPy, pull requests merged in 2022-06, with the labels that each got.

#2432 Remove "united" as meaning "having units"
  src/metpy/testing.py
  src/metpy/units.py
  tests/plots/test_skewt.py
  tests/plots/test_station_plot.py
  tests/units/test_units.py
Labels: Type: Maintenance

#2521 Configure dependabot for our composite actions
  .github/dependabot.yml
Labels: Area: Infrastructure, Type: Enhancement

#2528 Ignore EHP heat index reference in link check
  docs/conf.py
Labels: Type: Maintenance, Area: Docs

#2530 Add docstring examples for thickness_hydrostatic
  src/metpy/calc/thermo.py
Labels: Area: Docs, Type: Enhancement

#2529 Fix caching of PROJ build
  .github/actions/setup-proj/action.yml
Labels: Area: Infrastructure, Type: Bug

#2533 Fix PROJ caching
  .github/actions/setup-proj/action.yml
Labels: Area: Infrastructure, Type: Bug

#2527 Switch to mamba's "official" GitHub Action
  .github/actions/install-conda/action.yml
Labels: Area: Infrastructure, Type: Enhancement

#2531 Add missing CF projection variable to test file
  src/metpy/static-data-manifest.txt
  staticdata/GFS_test.nc
Labels: Type: Maintenance

#2532 Shapely build
  .github/actions/install-pypi/action.yml
Labels: Area: Infrastructure, Type: Enhancement

#2558 Add a GHA workflow to backport PRs
  .circleci/config.yml
  .github/workflows/assign-milestone.yml
  .github/workflows/backport-prs.yml
  .github/workflows/docs-conda.yml
  .github/workflows/linting.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
Labels: Area: Infrastructure, Type: Feature

#2560 CI: Synchronize infrastructure from main
  .github/actions/build-docs/action.yml
  .github/actions/install-conda/action.yml
  .github/actions/install-pypi/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/setup-proj/action.yml
  .github/workflows/assign-milestone.yml
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/linting.yml
  .github/workflows/release.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  ci/doc_requirements.txt
  ci/extra_requirements.txt
  ci/filter_links.py
  ci/requirements.txt
  ci/test_requirements.txt
  tests/plots/baseline/test_colorfill.png
  tests/plots/baseline/test_colorfill_horiz_colorbar.png
  tests/plots/baseline/test_colorfill_no_colorbar.png
  tests/plots/baseline/test_declarative_events.png
  tests/plots/baseline/test_declarative_sfc_text.png
  tests/plots/baseline/test_declarative_upa_obs.png
  tests/plots/baseline/test_declarative_upa_obs_convert_barb_units.png
  tests/plots/test_declarative.py
Labels: Area: Infrastructure, Type: Maintenance
