Repository Unidata/MetPy, pull requests merged in 2022-01, with the labels that each got.

#2270 Handle truncated vertical visibility
  src/metpy/io/_metar_parser/metar_parser.peg
  src/metpy/io/_metar_parser/metar_parser.py
  src/metpy/io/metar.py
  tests/io/test_metar.py
Labels: Type: Bug, Area: IO

#2283 Fixing staticdata hash and testin
  .github/actions/build-docs/action.yml
  .github/actions/install-conda/action.yml
  .github/actions/run-tests/action.yml
  src/metpy/cbook.py
  src/metpy/static-data-manifest.txt
Labels: Area: Infrastructure, Type: Bug

#2286 Update git location for pip in nightly build
  .github/workflows/nightly-builds.yml
Labels: Area: Infrastructure, Type: Maintenance

#2288 Run nightly workflow when the file is modified
  .github/workflows/nightly-builds.yml
Labels: Area: Infrastructure, Type: Enhancement

#2263 Refactor moist_lapse
  src/metpy/calc/thermo.py
  src/metpy/plots/skewt.py
  tests/calc/test_thermo.py
  tests/plots/baseline/test_skewt_api_units.png
  tests/plots/baseline/test_skewt_default_aspect_empty.png
Labels: Type: Enhancement, Area: Calc

#2170 Validate declarative interface attributes
  src/metpy/plots/declarative.py
  tests/plots/test_declarative.py
Labels: Type: Enhancement, Area: Plots

#2271 Unit support for interpolation functions
  src/metpy/interpolate/points.py
  tests/interpolate/test_grid.py
  tests/interpolate/test_points.py
Labels: Type: Bug, Area: Calc, Area: Units

#2064 Improve some thermo calculation bottlenecks by refactoring how units are handled
  setup.cfg
  src/metpy/calc/thermo.py
  src/metpy/constants/__init__.py
  src/metpy/constants/default.py
  src/metpy/constants/nounit.py
  src/metpy/io/gempak.py
  src/metpy/units.py
  src/metpy/xarray.py
Labels: Type: Maintenance, Area: IO, Area: Calc, Area: Units

#2306 DOC: Update README installation guide URL
  README.md
Labels: Type: Bug, Area: Docs

#2307 GHA Workflow fixes from release
  .github/actions/build-docs/action.yml
  .github/workflows/docs.yml
  .github/workflows/nightly-builds.yml
Labels: Area: Infrastructure, Type: Bug

#2314 Use new allow_updates arg for pooch
  src/metpy/cbook.py
Labels: Area: Infrastructure, Type: Enhancement

#2316 Fix pooch argument handling for < 1.6.0
  setup.cfg
  src/metpy/cbook.py
Labels: Area: Infrastructure, Type: Bug

#2312 Retaining global attrs on MetPyDatasetAccessor.quantify()
  src/metpy/xarray.py
  tests/test_xarray.py
Labels: Type: Bug, Area: Units, Area: Xarray
