Repository Unidata/MetPy, pull requests merged in 2023-04, with the labels that each got.

#2979 Add ruff instructions to contributor's guide
  CONTRIBUTING.md
Labels: Type: Maintenance, Area: Docs

#2988 CI: Roll back to Pandas 1.5.3
  ci/requirements.txt
Labels: Area: Infrastructure, Type: Maintenance

#2990 CI: Remove deleted setup-proj action from dependabot
  .github/dependabot.yml
Labels: Area: Infrastructure, Type: Maintenance

#2994 unit redefinition help for /s
  src/metpy/units.py
  tests/units/test_units.py
Labels: Type: Enhancement, Area: Units

#2996 BUG: Fix up some legacy NEXRAD level 2 parsing issues
  src/metpy/io/nexrad.py
  src/metpy/static-data-manifest.txt
  staticdata/KLTX20050329_100015.gz
  tests/io/test_nexrad.py
Labels: Type: Bug, Area: IO

#2420 Fronts Plotting Support
  src/metpy/plots/__init__.py
  src/metpy/plots/patheffects.py
  tests/plots/baseline/test_curved_stationary.png
  tests/plots/baseline/test_fronts.png
  tests/plots/baseline/test_stationary_spacing.png
  tests/plots/test_patheffects.py
Labels: Type: Feature, Area: Plots

#2993 Address some linkchecker issues
  docs/conf.py
Labels: Area: Infrastructure, Type: Maintenance, Area: Docs

#2997 DOC: Add simple example plotting fronts using path effects
  examples/plots/Simple_Fronts_Plot.py
Labels: Area: Examples, Type: Enhancement

#1944 Function for parsing WPC coded surface bulletins
  examples/plots/Plotting_Surface_Analysis.py
  src/metpy/io/__init__.py
  src/metpy/io/text.py
  src/metpy/static-data-manifest.txt
  src/metpy/testing.py
  staticdata/WPC_sfc_fronts_20210628_1800.txt
  staticdata/WPC_sfc_fronts_lowres_20210628_1800.txt
  tests/io/test_text.py
Labels: Type: Feature, Area: IO

#3009 Fix formatting of "Returns" from most_unstable_parcel
  src/metpy/calc/thermo.py
Labels: Type: Bug, Area: Docs

#3018 Update METAR link to use production TDS
  examples/plots/Station_Plot.py
Labels: Type: Maintenance, Area: Examples
