Repository Unidata/MetPy, pull requests merged in 2023-05, with the labels that each got.

#3024 Improve GEMPAK "thinned GFS" files
  src/metpy/plots/mapping.py
  tests/plots/test_mapping.py
Labels: Type: Bug, Area: Projections

#2992 Add scalloped path effect
  src/metpy/plots/patheffects.py
  tests/plots/baseline/test_scalloped_stroke_closed.png
  tests/plots/baseline/test_scalloped_stroke_segment.png
  tests/plots/test_patheffects.py
Labels: Type: Feature, Area: Plots

#2999 Use weighted_continuous_average in bunkers_storm_motion
  src/metpy/calc/indices.py
  tests/calc/test_indices.py
Labels: Type: Maintenance, Area: Calc

#3026 DOC: Simplify docstring example
  src/metpy/calc/basic.py
Labels: Area: Docs, Type: Enhancement

#3003 Additional path effects
  src/metpy/plots/patheffects.py
  tests/plots/baseline/test_frontogenesis.png
  tests/plots/baseline/test_frontolysis.png
  tests/plots/baseline/test_special.png
  tests/plots/test_patheffects.py
Labels: Type: Feature, Area: Plots

#3025 BUG: Raise error in moist_lapse on solver fail
  ci/test_requirements.txt
  pyproject.toml
  src/metpy/calc/thermo.py
  tests/calc/test_thermo.py
Labels: Type: Bug, Area: Calc

#2949 Update areas
  docs/Makefile
  docs/api/index.rst
  docs/conf.py
  docs/make.bat
  docs/make_areas.py
  src/metpy/plots/__init__.py
  src/metpy/plots/declarative.py
  src/metpy/plots/plot_areas.py
  tests/plots/baseline/test_au_plotting.png
  tests/plots/baseline/test_cn_plotting.png
  tests/plots/baseline/test_hi_plotting.png
  tests/plots/baseline/test_uslcc_plotting.png
  tests/plots/baseline/test_wpac_plotting.png
  tests/plots/test_plot_areas.py
  tutorials/area_tutorial.py
Labels: Type: Enhancement

#3038 DOC: manually add PST version json
  pst-versions.json
Labels: Area: Infrastructure, Type: Maintenance, Area: Docs

#3045 Export parse_wpc_surface_bulletin
  src/metpy/io/__init__.py
  src/metpy/io/text.py
Labels: Type: Bug, Area: IO

#3051 CI: Migrate to mamba-org/setup-micromamba
  .github/actions/install-conda/action.yml
Labels: Area: Infrastructure, Type: Maintenance
