Repository Unidata/MetPy, pull requests merged in 2023-07, with the labels that each got.

#3103 Fix interpolation with mixed types
  src/metpy/interpolate/one_dimension.py
  tests/interpolate/test_one_dimension.py
Labels: Type: Bug, Area: Units, Area: Gridding

#3098 Fix fronts
  src/metpy/plots/patheffects.py
  tests/plots/baseline/test_curved_stationary.png
  tests/plots/baseline/test_fronts.png
  tests/plots/baseline/test_stationary_spacing.png
Labels: Type: Bug, Area: Plots

#3107 Drop Python 3.8
  .github/workflows/docs-conda.yml
  .github/workflows/docs.yml
  .github/workflows/tests-conda.yml
  .github/workflows/tests-pypi.yml
  README.md
  ci/requirements.txt
  docs/index.rst
  docs/userguide/installguide.rst
  pyproject.toml
  src/metpy/interpolate/one_dimension.py
  src/metpy/io/gempak.py
  src/metpy/plots/_util.py
  src/metpy/plots/ctables.py
  src/metpy/plots/wx_symbols.py
Labels: Area: Infrastructure, Type: Maintenance

#3118 Practical units for dry adiabatic lapse rate constant
  src/metpy/constants/default.py
Labels: Type: Enhancement, Area: Calc, Area: Units

#3119 Add string formatting information to unit tutorial
  tutorials/unit_tutorial.py
Labels: Area: Docs, Type: Enhancement

#3114 Update CCL/EL/LFC docstring to reflect that pressure should be monotonically decreasing
  src/metpy/calc/thermo.py
Labels: Area: Docs, Type: Enhancement, Area: Calc

#3125 Bump the copyright year in the license file
  LICENSE
Labels: Type: Maintenance, Area: Docs

#3123 Add rotated latitude longitude projection to mapping.py
  src/metpy/plots/mapping.py
  tests/plots/test_mapping.py
Labels: Type: Enhancement, Area: Projections

#3127 Add a dependabot group for flake8 and friends
  .github/dependabot.yml
Labels: Area: Infrastructure, Type: Enhancement
