Repository Unidata/MetPy, pull requests merged in 2024-03, with the labels that each got.

#3419 Fix version for docs on maintenance branch
  .github/actions/build-docs/action.yml
  docs/conf.py
Labels: Area: Infrastructure, Type: Bug

#3431 GEMPAK performance updates
  .codespellignore
  src/metpy/io/gempak.py
  src/metpy/static-data-manifest.txt
  staticdata/gem_big_endian.grd
  staticdata/gem_climate.csv
  staticdata/gem_climate.sfc
  staticdata/gem_little_endian.grd
  staticdata/gem_merged_nopack.csv
  staticdata/gem_merged_nopack.snd
  staticdata/gem_multilevel_multidate.grd
  tests/io/test_gempak.py
Labels: Type: Enhancement, Area: IO

#3437 Make coordinate detection more robust
  src/metpy/xarray.py
  tests/test_xarray.py
Labels: Type: Enhancement, Area: Xarray

#3448 angle_to_direction handle ndarray
  src/metpy/calc/tools.py
  tests/calc/test_calc_tools.py
Labels: Area: Calc, Area: Xarray

#3451 Note text-mode needed for METAR file-like objects
  src/metpy/io/metar.py
Labels: Area: Docs, Type: Enhancement, Area: IO
