Repository Unidata/MetPy, pull requests merged in 2025-07, with the labels that each got.

#3872 Set up Qlty
  .codeclimate.yml
  .markdownlint.yaml
  .qlty/qlty.toml
  README.md
  docs/conf.py
  docs/devel/infrastructureguide.rst
  src/metpy/plots/fonts/wx_symbols_license.txt
  tutorials/README.md
Labels: Area: Infrastructure, Type: Maintenance

#3880 Use app token for Dependabot auto-merge
  .github/workflows/automerge-dependabot.yml
Labels: Area: Infrastructure, Type: Bug

#3890 Update Jenkinsfile - using withCredentials correctly for a deploy key
  benchmarks/Jenkinsfile
Labels: Area: Infrastructure, Type: Maintenance

#3889 GitHub Action to Comparatively Benchmark PRs
  .github/workflows/benchmark-pr.yml
  docs/devel/benchmarking.rst
Labels: Area: Infrastructure, Type: Enhancement, benchmark

#3893 Forcing Jenkins to actually use the ssh key
  benchmarks/Jenkinsfile
Labels: Area: Infrastructure, Type: Maintenance
