Repository Unidata/MetPy, pull requests merged in 2025-05, with the labels that each got.

#3807 Update version listing and latest link
  latest
  pst-versions.json
  versions.json
Labels: Type: Maintenance, Area: Docs

#3815 BUG: Fix handling rotated pole (lat/lon) parsing
  src/metpy/plots/mapping.py
  src/metpy/xarray.py
  tests/test_xarray.py
Labels: Type: Bug, Area: Projections

#3810 Fix missing blank line in test_requirements.txt
  ci/test_requirements.txt
Labels: Area: Infrastructure, Type: Bug

#3818 Fix doc version handling on deployment
  .github/workflows/docs.yml
Labels: Area: Infrastructure, Type: Enhancement

#3822 CI: Fix dependabot ignoring some updates
  .python-version
Labels: Area: Infrastructure, Type: Maintenance

#3831 Dependabot updates
  .devcontainer/Dockerfile
  .github/actions/install-conda/action.yml
  .github/actions/install-pypi/action.yml
  .github/dependabot.yml
  .github/workflows/linting.yml
  .github/workflows/tests-pypi.yml
  .github/workflows/unstable-builds.yml
  CONTRIBUTING.md
  ci/dev/doc_requirements.txt
  ci/dev/linting_requirements.txt
  ci/dev/test_requirements.txt
  ci/extra_requirements.txt
  pyproject.toml
Labels: Area: Infrastructure, Type: Maintenance

#3836 More dependabot updates
  .github/dependabot.yml
Labels: Area: Infrastructure, Type: Maintenance

#3837 Fix dependabot syntax
  .github/dependabot.yml
Labels: Area: Infrastructure, Type: Bug
